init main-trigger-on-approve

diff --git a/.github/workflows/pull_request_review.yaml b/.github/workflows/pull_request_review.yaml
--- a/.github/workflows/pull_request_review.yaml
+++ b/.github/workflows/pull_request_review.yaml
@@ -2,7 +2,7 @@ name: Pull request
 
 on:
   workflow_dispatch:
-  pull_request:
+  pull_request_review:
 
 jobs:
   # event:
@@ -14,12 +14,17 @@ jobs:
   #         echo $EVENT_CONTEXT | jq .
 
   # We don't fail "myjob" here
-  validation:
+  pipeline:
     runs-on: ubuntu-latest
+    if: github.event.review.state == 'approved'
     steps:
       - run: |
-          echo "Running validation."
-          sleep 3
+          echo "Creating artifact..."
+          sleep 10
           echo "Done"
+      - if: contains(github.event.pull_request.title , 'fail')
+        run: |
+          echo "::error ::Failing...."
+          exit 1
 
     
